- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Matomo database
  mysql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present

- name: Change max_allowed_packet size to 64MB
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^\s*max_allowed_packet\s+=\s+(\d+)M.*$'
    line: 'max_allowed_packet = 64M'
    backrefs: yes
  notify: Restart MySQL
