- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: true

- name: Enable automatic secruity upgrades
  command: unattended-upgrade
  ignore_errors: yes
